version: '2'
services:
  db:
    restart: always
    image: postgres:9.6-alpine

  web:
    restart: always
    image: aircall:development
    build:
      context: .
      args:
        bundle-without: production
    env_file: dev.env
    environment:
      RAILS_ENV: development
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
      - "8000:3000"
    tty: true
    stdin_open: true
    links:
      - db
    volumes:
      - ./sources:/aircall
